[package]
name = "daedalus"
version = "0.1.0"
authors = ["Keith Yeung <kungfukeith11@gmail.com>"]
edition = "2018"

[dependencies]
csv = "1.1"
serde = { version = "1", features = ["derive"] }
structopt = "0.3"
